// Generated by scripts/generate-themes.ts. Do not edit.
import type { Theme } from "@preman/desktop/renderer/appearance/theme.js";
import { premanDark } from "./preman-dark.js";
import { auraDark } from "./aura-dark.js";
import { auraLight } from "./aura-light.js";
import { ayuDark } from "./ayu-dark.js";
import { ayuLight } from "./ayu-light.js";
import { carbonfoxDark } from "./carbonfox-dark.js";
import { carbonfoxLight } from "./carbonfox-light.js";
import { catppuccinDark } from "./catppuccin-dark.js";
import { catppuccinLight } from "./catppuccin-light.js";
import { draculaDark } from "./dracula-dark.js";
import { draculaLight } from "./dracula-light.js";
import { fieldsOfTheShireDark } from "./fields-of-the-shire-dark.js";
import { fieldsOfTheShireLight } from "./fields-of-the-shire-light.js";
import { flexokiDark } from "./flexoki-dark.js";
import { flexokiLight } from "./flexoki-light.js";
import { gruvboxDark } from "./gruvbox-dark.js";
import { gruvboxLight } from "./gruvbox-light.js";
import { jetbrainsDark } from "./jetbrains-dark.js";
import { jetbrainsLight } from "./jetbrains-light.js";
import { kanagawaDark } from "./kanagawa-dark.js";
import { kanagawaLight } from "./kanagawa-light.js";
import { monoDark } from "./mono-dark.js";
import { monoLight } from "./mono-light.js";
import { monoPlusDark } from "./mono-plus-dark.js";
import { monoPlusLight } from "./mono-plus-light.js";
import { monokaiDark } from "./monokai-dark.js";
import { monokaiLight } from "./monokai-light.js";
import { nightowlDark } from "./nightowl-dark.js";
import { nightowlLight } from "./nightowl-light.js";
import { nordDark } from "./nord-dark.js";
import { nordLight } from "./nord-light.js";
import { onedarkproDark } from "./onedarkpro-dark.js";
import { onedarkproLight } from "./onedarkpro-light.js";
import { openchamberDark } from "./openchamber-dark.js";
import { openchamberLight } from "./openchamber-light.js";
import { solarizedDark } from "./solarized-dark.js";
import { solarizedLight } from "./solarized-light.js";
import { tokyonightDark } from "./tokyonight-dark.js";
import { tokyonightLight } from "./tokyonight-light.js";
import { vesperDark } from "./vesper-dark.js";
import { vesperLight } from "./vesper-light.js";
import { vitesseDarkDark } from "./vitesse-dark-dark.js";
import { vitesseLightLight } from "./vitesse-light-light.js";

/** Every bundled theme, "preman-dark" first because it is the default. */
export const THEMES: readonly Theme[] = [
  premanDark,
  auraDark,
  auraLight,
  ayuDark,
  ayuLight,
  carbonfoxDark,
  carbonfoxLight,
  catppuccinDark,
  catppuccinLight,
  draculaDark,
  draculaLight,
  fieldsOfTheShireDark,
  fieldsOfTheShireLight,
  flexokiDark,
  flexokiLight,
  gruvboxDark,
  gruvboxLight,
  jetbrainsDark,
  jetbrainsLight,
  kanagawaDark,
  kanagawaLight,
  monoDark,
  monoLight,
  monoPlusDark,
  monoPlusLight,
  monokaiDark,
  monokaiLight,
  nightowlDark,
  nightowlLight,
  nordDark,
  nordLight,
  onedarkproDark,
  onedarkproLight,
  openchamberDark,
  openchamberLight,
  solarizedDark,
  solarizedLight,
  tokyonightDark,
  tokyonightLight,
  vesperDark,
  vesperLight,
  vitesseDarkDark,
  vitesseLightLight,
];
