/**
 * Turn the vendored palettes into audited theme modules. Run by hand:
 *
 *   bun run packages/desktop/scripts/generate-themes.ts
 *
 * By hand, and not as a build step, for the same reason `resources/generate.swift` is: a build
 * step nobody inspects the output of is a build step that hides a bad colour. The output is
 * committed, so a reviewer sees the hex that changed rather than a script that changed.
 *
 * It lives outside `src/renderer/` because it needs `node:fs` and the renderer fence forbids
 * `node:*` there. Its output is pure data and belongs inside.
 *
 * Three of the twenty-one colours are *solved*, not read: `ink-dim`, `ink-faint` and `glyph` have
 * no source field, and are faded from `ink` toward `canvas` until the measured worst case against
 * all five surfaces lands on the target. That is the whole point of generating rather than
 * transcribing — the contrast contract in `app.css` stops being a comment describing one palette
 * and becomes a property that holds for every palette.
 *
 * `config.fonts` in the source is dropped, deliberately. One Dark Pro's `sans` is a *monospace*
 * stack, so importing it would mean picking a theme silently changed the UI's typeface. Theme is
 * colour, font is font; they travel together in someone else's file format and that is not a
 * reason to couple them here.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import {
  CONTRAST_TARGET,
  LADDER_TOKENS,
  METHOD_MIN_DISTANCE,
  METHOD_TOKENS,
  SURFACE_MIN_STEP,
  TEMPLATE_MIN_DISTANCE,
  TEMPLATE_NEIGHBOURS,
  auditTheme,
  contrast,
  fadeToTarget,
  flatten,
  fromOklch,
  luminance,
  mix,
  oklch,
  parseColor,
  perceptualDistance,
  toHex,
  toLuminance,
  BLACK,
  WHITE,
  type AuditableTheme,
  type Rgb,
} from "./audit.js";

const here = dirname(fileURLToPath(import.meta.url));
const PALETTE_DIR = join(here, "palettes");
const OUTPUT_DIR = join(here, "../src/renderer/appearance/themes");
const OVERRIDE_FILE = join(PALETTE_DIR, "overrides.json");
const JSON_EXTENSION = ".json";
const ENCODING = "utf8";
const HEADER = "// Generated by scripts/generate-themes.ts. Do not edit.";
const HAND_WRITTEN = "preman-dark";

/**
 * Aim above the floor the audit enforces. Every value is rounded to eight bits on the way out, and
 * a solver that lands exactly on 4.500 produces a file that measures 4.497.
 */
const MARGIN = 1.02;
/** The ladder is built with more room than the audit demands, for the same reason. */
const LADDER_STEP = 1.06;
/**
 * How far `selected` is pulled toward the accent. `app.css` is explicit that selection reads as
 * "the accent is here" rather than "this grey is 8% off", and this is that sentence as a number.
 */
const SELECTION_TINT = 0.4;
/** Alpha and depth of `--shadow-float`, per variant. A dark shadow on a light canvas is a bruise. */
const SHADOW = {
  dark: { toward: 0.47, alpha: 0.55 },
  light: { toward: 0.7, alpha: 0.16 },
} as const;
const SHADOW_GEOMETRY = "0 4px 12px";
const SOLVER_STEPS = 40;
const HALF = 2;
const FLARE = 0.05;
const OPAQUE_WHITE_LUMINANCE = 1;
const ALPHA_DECIMALS = 2;
const LADDER_LAST = LADDER_TOKENS.length - 1;
const EXIT_FAILURE = 1;

/** Everything the converter reads out of a palette. Anything absent is an error, not a default. */
interface Palette {
  readonly metadata: { readonly id: string; readonly name: string; readonly variant: string };
  readonly colors: {
    readonly primary: Record<string, string>;
    readonly surface: Record<string, string>;
    readonly interactive: Record<string, string>;
    readonly status: Record<string, string>;
    readonly pr: Record<string, string>;
    readonly syntax: {
      readonly base: Record<string, string>;
      readonly tokens: Record<string, string>;
      readonly highlights: Record<string, string>;
    };
    readonly markdown: Record<string, string>;
  };
}

type Overrides = Record<string, { colors?: Record<string, string>; syntax?: Record<string, string> }>;

/**
 * Who to credit, keyed by the family an id belongs to.
 *
 * The palettes are third-party twice over: each is somebody's colour scheme, and the JSON rendition
 * of it is openchamber's. `palettes/NOTICE` says so at length; these two fields put the same fact
 * on the record itself, so a settings pane can show it without reading a file.
 */
const ATTRIBUTION: Record<string, { source: string; licence: string }> = {
  aura: { source: "Aura Theme, daltonmenezes", licence: "MIT" },
  ayu: { source: "Ayu, dempfi", licence: "MIT" },
  carbonfox: { source: "Nightfox, EdenEast", licence: "MIT" },
  catppuccin: { source: "Catppuccin", licence: "MIT" },
  dracula: { source: "Dracula, Zeno Rocha", licence: "MIT" },
  "fields-of-the-shire": { source: "Fields of the Shire, openchamber", licence: "MIT" },
  flexoki: { source: "Flexoki, Steph Ango", licence: "MIT" },
  gruvbox: { source: "gruvbox, morhetz", licence: "MIT" },
  jetbrains: { source: "JetBrains Darcula / IntelliJ Light", licence: "Apache-2.0" },
  kanagawa: { source: "Kanagawa, rebelot", licence: "MIT" },
  mono: { source: "Mono, openchamber", licence: "MIT" },
  "mono-plus": { source: "Mono+, openchamber", licence: "MIT" },
  monokai: { source: "Monokai, Wimer Hazenberg", licence: "MIT" },
  nightowl: { source: "Night Owl, Sarah Drasner", licence: "MIT" },
  nord: { source: "Nord, Arctic Ice Studio", licence: "MIT" },
  onedarkpro: { source: "One Dark Pro, binaryify", licence: "MIT" },
  openchamber: { source: "openchamber", licence: "MIT" },
  solarized: { source: "Solarized, Ethan Schoonover", licence: "MIT" },
  tokyonight: { source: "Tokyo Night, enkia", licence: "MIT" },
  vesper: { source: "Vesper, Rauno Freiberg", licence: "MIT" },
  vitesse: { source: "Vitesse, Anthony Fu", licence: "MIT" },
};

/**
 * Where each colour comes from, and what it falls back to when a palette does not carry it.
 *
 * Four of the forty-two palettes ship a partial `syntax.tokens`. A fallback at *generation* time is
 * not the runtime fallback `theme.ts` forbids: the committed file still holds all thirty-five
 * values, and which value a missing token resolved to is visible in the diff.
 */
interface SyntaxSource {
  /** `[group, key]` inside `colors.syntax`. */
  readonly from: readonly [string, string];
  readonly or?: readonly [string, string];
}

const SYNTAX_SOURCES: Record<string, SyntaxSource> = {
  comment: { from: ["base", "comment"] },
  "comment-doc": { from: ["tokens", "commentDoc"], or: ["base", "comment"] },
  keyword: { from: ["base", "keyword"] },
  "keyword-import": { from: ["tokens", "keywordImport"], or: ["base", "keyword"] },
  "storage-modifier": { from: ["tokens", "storageModifier"], or: ["base", "keyword"] },
  atom: { from: ["tokens", "boolean"], or: ["base", "number"] },
  number: { from: ["base", "number"] },
  string: { from: ["base", "string"] },
  "string-escape": { from: ["tokens", "stringEscape"], or: ["base", "string"] },
  regex: { from: ["tokens", "regex"], or: ["base", "string"] },
  operator: { from: ["base", "operator"] },
  punctuation: { from: ["tokens", "punctuation"], or: ["base", "foreground"] },
  bracket: { from: ["tokens", "punctuation"], or: ["base", "foreground"] },
  variable: { from: ["base", "variable"] },
  parameter: { from: ["tokens", "parameter"], or: ["base", "variable"] },
  property: { from: ["tokens", "key"], or: ["base", "variable"] },
  constant: { from: ["tokens", "constant"], or: ["base", "number"] },
  function: { from: ["base", "function"] },
  method: { from: ["tokens", "method"], or: ["base", "function"] },
  type: { from: ["base", "type"] },
  "class-name": { from: ["tokens", "className"], or: ["base", "type"] },
  namespace: { from: ["tokens", "namespace"], or: ["base", "type"] },
  decorator: { from: ["tokens", "decorator"], or: ["base", "type"] },
  label: { from: ["tokens", "label"], or: ["base", "variable"] },
  macro: { from: ["tokens", "macro"], or: ["base", "keyword"] },
  "tag-name": { from: ["tokens", "tag"], or: ["base", "keyword"] },
  "attribute-name": { from: ["tokens", "tagAttribute"], or: ["base", "type"] },
  "attribute-value": { from: ["tokens", "tagAttributeValue"], or: ["base", "string"] },
  url: { from: ["tokens", "url"], or: ["base", "string"] },
  "diff-added": { from: ["highlights", "diffAdded"], or: ["base", "string"] },
  "diff-modified": { from: ["highlights", "diffModified"], or: ["base", "keyword"] },
  "diff-removed": { from: ["highlights", "diffRemoved"], or: ["base", "number"] },
};

/** `invalid`, `heading` and `link` are not syntax in the source format; they come from elsewhere. */
const SYNTAX_ELSEWHERE = ["invalid", "heading", "link"] as const;

function read(record: Record<string, string>, key: string, where: string): string {
  const value = record[key];
  if (value === undefined) throw new Error(`${where} has no ${key}`);
  return value;
}

/** Every source colour is composited over the surface it would sit on, because preman's are solid. */
function opaque(value: string, base: Rgb): Rgb {
  return flatten(parseColor(value), base);
}

/**
 * Push a colour away from `surfaces` until the worst ratio clears `target`.
 *
 * Toward white on a dark theme and toward black on a light one, which is the only direction that
 * raises contrast against every surface at once. Monotonic, so a bisection is exact; if even the
 * extreme cannot reach the target the extreme is returned and the audit says so.
 */
function escalate(colour: Rgb, surfaces: readonly Rgb[], target: number, extreme: Rgb): Rgb {
  const worst = (candidate: Rgb): number => Math.min(...surfaces.map((surface) => contrast(candidate, surface)));
  if (worst(colour) >= target) return colour;
  if (worst(extreme) < target) return extreme;
  let low = 0;
  let high = 1;
  for (let step = 0; step < SOLVER_STEPS; step += 1) {
    const middle = (low + high) / HALF;
    if (worst(mix(colour, extreme, middle)) >= target) high = middle;
    else low = middle;
  }
  return mix(colour, extreme, high);
}

/**
 * The four ladder surfaces, re-spaced.
 *
 * Two things have to hold at once and a palette guarantees neither. Each step has to be visible,
 * or hovering a row does nothing. And `hover` — the surface furthest from the canvas, and so the
 * worst case for every foreground tier — has to stay inside the window where `ink` can still reach
 * 10.8:1, or no ink solves. Working in `luminance + flare` makes both statements arithmetic: a
 * contrast ratio between two surfaces is exactly the quotient of their values in that space.
 */
function respaceLadder(seeds: readonly Rgb[], lighter: boolean): Rgb[] {
  const flared = seeds.map((seed) => luminance(seed) + FLARE);
  const first = flared[0] ?? FLARE;
  const values = [first];
  for (let index = 1; index < flared.length; index += 1) {
    const previous = values[index - 1] ?? first;
    const seed = flared[index] ?? previous;
    values.push(lighter ? Math.max(seed, previous * LADDER_STEP) : Math.min(seed, previous / LADDER_STEP));
  }

  // The reachability window: what `hover` may be if pure white (or pure black) is to clear the ink
  // target against it. `ink` is never pure, so the margin buys the palette's own hue some room.
  const limit = lighter
    ? (OPAQUE_WHITE_LUMINANCE + FLARE) / (CONTRAST_TARGET.ink * MARGIN)
    : FLARE * CONTRAST_TARGET.ink * MARGIN;
  const last = values[LADDER_LAST] ?? first;
  if (lighter ? last > limit : last < limit) {
    // Redistribute the whole run geometrically between the fixed canvas and the limit, so the
    // steps stay equal instead of the squeeze landing entirely on the last one.
    const span = limit / first;
    for (let index = 1; index < values.length; index += 1) {
      values[index] = first * Math.pow(span, index / LADDER_LAST);
    }
  }

  return values.map((value, index) => toLuminance(seeds[index] ?? BLACK, value - FLARE));
}

/**
 * Where each verb's colour comes from, in preference order.
 *
 * More than one candidate each because a palette's semantic slots collide constantly: half of them
 * set `primary.base` and `status.info` to the same blue, and Vesper sets four of the six to the
 * same amber. The syntax palette is the second choice everywhere, and it is a good one — making
 * tokens tell each other apart is the entire job of a syntax theme, so its hues are the ones a
 * palette actually spent its variety on.
 */
const METHOD_SOURCES: Record<(typeof METHOD_TOKENS)[number], readonly string[]> = {
  "method-get": ["status.success", "syntax.base.string", "pr.open", "syntax.tokens.method"],
  "method-post": ["status.warning", "syntax.base.number", "pr.blocked", "syntax.tokens.decorator"],
  "method-put": ["primary.base", "syntax.base.function", "status.info", "syntax.tokens.key"],
  "method-patch": ["pr.merged", "syntax.base.keyword", "syntax.tokens.storageModifier", "markdown.blockquote"],
  "method-delete": ["status.error", "syntax.base.operator", "syntax.tokens.exception", "pr.closed"],
  "method-grpc": ["status.info", "syntax.tokens.constant", "syntax.base.type", "markdown.link"],
};

/** Hue rotations tried, in whole turns of this many, when no candidate in the pool is far enough. */
const HUE_STEPS = 36;
const TURN = Math.PI * HALF;
/** Lightness nudges tried when a palette has no hue to rotate — the monochrome case. */
const LIGHTNESS_STEP = 0.03;
const LIGHTNESS_MOVES = 12;
/**
 * How many times the six are swept after the first pass. A greedy assignment is order-dependent —
 * the sixth verb pays for every choice above it — so the run is repeated until nothing moves.
 */
const REPAIR_ROUNDS = 6;

/** OKLab lightness of the extreme a colour is escalated toward; the top of the usable range. */
const LIGHTEST = 1;
const DARKEST = 0;

const NEUTRAL = (lightness: number): Rgb => fromOklch({ l: lightness, c: 0, h: 0 });

/**
 * The band of the OKLab lightness axis a colour can sit in and still clear the method target.
 * Bisected rather than tabulated because it depends on the theme's own canvas and panel.
 *
 * `at` builds the colour under test from a lightness. It defaults to a grey, which is what the
 * monochrome method fallback wants; pass the hue and chroma to hold when placing one token.
 */
function readableBand(readable: (colour: Rgb) => boolean, at: (lightness: number) => Rgb = NEUTRAL): [number, number] {
  const lighter = readable(at(LIGHTEST));
  let inside = lighter ? LIGHTEST : DARKEST;
  let outside = lighter ? DARKEST : LIGHTEST;
  for (let step = 0; step < SOLVER_STEPS; step += 1) {
    const middle = (inside + outside) / HALF;
    if (readable(at(middle))) inside = middle;
    else outside = middle;
  }
  return lighter ? [inside, LIGHTEST] : [DARKEST, inside];
}

/**
 * The four measurements every "these colours must not look alike" solver needs, bound to one
 * theme's surfaces. Extracted because two columns want them: the six verbs, and the template token
 * that has to stay clear of string, number and property.
 */
interface Separator {
  /** Raise a colour until it clears the method contrast target on both surfaces. */
  readonly legible: (colour: Rgb) => Rgb;
  /** Whether it already does. */
  readonly readable: (colour: Rgb) => boolean;
  /** OKLab distance to the nearest colour already taken; infinite when nothing is. */
  readonly spread: (colour: Rgb, taken: readonly Rgb[]) => number;
  /** Every legible move away from a colour, nearest first. */
  readonly moves: (colour: Rgb) => Rgb[];
}

function separator(canvas: Rgb, panel: Rgb, extreme: Rgb): Separator {
  const legible = (colour: Rgb): Rgb => escalate(colour, [canvas, panel], CONTRAST_TARGET.method * MARGIN, extreme);
  const readable = (colour: Rgb): boolean =>
    Math.min(contrast(colour, canvas), contrast(colour, panel)) >= CONTRAST_TARGET.method * MARGIN;
  const spread = (colour: Rgb, taken: readonly Rgb[]): number =>
    taken.length === 0
      ? Number.POSITIVE_INFINITY
      : Math.min(...taken.map((other) => perceptualDistance(colour, other)));

  /**
   * Every way this colour is allowed to move, nearest first: the hue circle in both directions by
   * a widening angle, then lightness in both directions by a widening step. The order is the whole
   * point — the caller takes the first move that clears the threshold, so a verb that only needs a
   * ten degree turn gets a ten degree turn instead of the move that happens to score highest.
   */
  const moves = (colour: Rgb): Rgb[] => {
    const polar = oklch(colour);
    const both = <T>(count: number, at: (signed: number) => T): T[] =>
      Array.from({ length: count }, (_unused, step) => [at(step + 1), at(-(step + 1))]).flat();
    return [
      ...both(HUE_STEPS / HALF, (signed) => fromOklch({ ...polar, h: polar.h + (TURN * signed) / HUE_STEPS })),
      ...both(LIGHTNESS_MOVES, (signed) => fromOklch({ ...polar, l: polar.l + LIGHTNESS_STEP * signed })),
    ].filter(readable);
  };

  return { legible, readable, spread, moves };
}

function dotted(source: Palette["colors"], path: string): string | undefined {
  let node: unknown = source;
  for (const key of path.split(".")) {
    if (typeof node !== "object" || node === null) return undefined;
    node = (node as Record<string, unknown>)[key];
  }
  return typeof node === "string" ? node : undefined;
}

/**
 * The six verb colours, guaranteed to be six colours.
 *
 * The sidebar, the tab strip and the method picker all show the whole set within a few hundred
 * pixels of each other, so two verbs that are the same colour is not a subtle loss — it is a row
 * that lies about what it will send. Read the preferred source, take the next candidate when it
 * collides, and when the palette has run out of hues, move the colour itself: rotate it in OKLCh,
 * which holds the palette's own lightness and saturation, and fall back to lightness for a
 * monochrome palette, where lightness is the only axis it has.
 */
function methodColumn(source: Palette["colors"], canvas: Rgb, panel: Rgb, extreme: Rgb): Record<string, string> {
  const { legible, readable, spread, moves } = separator(canvas, panel, extreme);

  const chosen: Rgb[] = [];
  for (const token of METHOD_TOKENS) {
    const candidates = (METHOD_SOURCES[token] ?? [])
      .map((path) => dotted(source, path))
      .filter((value): value is string => value !== undefined)
      .map((value) => legible(flatten(parseColor(value), canvas)));
    const preferred = candidates[0] ?? legible(canvas);
    chosen.push(
      candidates.find((candidate) => spread(candidate, chosen) >= METHOD_MIN_DISTANCE) ??
        candidates.reduce(
          (best, candidate) => (spread(candidate, chosen) > spread(best, chosen) ? candidate : best),
          preferred,
        ),
    );
  }

  for (let round = 0; round < REPAIR_ROUNDS; round += 1) {
    let moved = false;
    for (const [index, colour] of chosen.entries()) {
      const others = chosen.filter((_unused, other) => other !== index);
      if (spread(colour, others) >= METHOD_MIN_DISTANCE) continue;
      const candidates = moves(colour);
      const improved =
        candidates.find((candidate) => spread(candidate, others) >= METHOD_MIN_DISTANCE) ??
        candidates.reduce(
          (best, candidate) => (spread(candidate, others) > spread(best, others) ? candidate : best),
          colour,
        );
      if (improved === colour) continue;
      chosen[index] = improved;
      moved = true;
    }
    if (!moved) break;
  }

  // The monochrome case. A palette with no chroma has nothing for a hue rotation to turn, so the
  // only axis left is the one it does have: spread all six evenly up the readable lightness range,
  // in the order they already sit in. Ranking rather than reassigning keeps GET lighter than POST
  // if that is how the palette had it, and the even spacing is what the pairwise rule asks for.
  const others = (index: number): Rgb[] => chosen.filter((_unused, other) => other !== index);
  if (chosen.some((colour, index) => spread(colour, others(index)) < METHOD_MIN_DISTANCE)) {
    const [low, high] = readableBand(readable);
    const rank = chosen.map((colour, index) => ({ index, l: oklch(colour).l })).sort((a, b) => a.l - b.l);
    for (const [position, entry] of rank.entries()) {
      const polar = oklch(chosen[entry.index] ?? canvas);
      const share = position / (METHOD_TOKENS.length - 1);
      chosen[entry.index] = fromOklch({ ...polar, l: low + (high - low) * share });
    }
  }

  return Object.fromEntries(METHOD_TOKENS.map((token, index) => [token, toHex(chosen[index] ?? canvas)]));
}

/**
 * Where to look for `--syntax-template`, in order of preference.
 *
 * A `{{token}}` is not a language construct, so no palette has a slot for it. What it *is* is the
 * one span in a request body that will be something else by the time it is sent, which is the same
 * job a macro or a decorator does in a language: a marker that this text is about to be replaced.
 * Those are the slots a palette is most likely to have spent a distinct hue on, and the ones a
 * reader already reads as "not literal".
 */
const TEMPLATE_SOURCES: readonly string[] = [
  "syntax.tokens.macro",
  "syntax.tokens.decorator",
  "syntax.base.variable",
  "markdown.inlineCode",
  "status.info",
  "pr.draft",
];

/**
 * The one colour that has to stand apart from three specific others.
 *
 * A token appears exactly where a string or a number would, often on the same line as both, and
 * every key around it is `property` — so unlike the method column, whose members only have to
 * differ from each other, this one has three fixed neighbours it must clear and no say in where
 * they sit. Measured, not assumed: four of the vendored palettes give `macro` and `property` the
 * same hex, so reading the preferred source and stopping would have shipped a token that is
 * invisible as a token in those four.
 */
function templateColour(
  source: Palette["colors"],
  neighbours: readonly Rgb[],
  canvas: Rgb,
  panel: Rgb,
  extreme: Rgb,
): string {
  const { legible, readable, spread, moves } = separator(canvas, panel, extreme);
  const clear = (colour: Rgb): boolean => spread(colour, neighbours) >= TEMPLATE_MIN_DISTANCE;
  const furthest = (from: Rgb, pool: readonly Rgb[]): Rgb =>
    pool.reduce(
      (best, candidate) => (spread(candidate, neighbours) > spread(best, neighbours) ? candidate : best),
      from,
    );

  const candidates = TEMPLATE_SOURCES.map((path) => dotted(source, path))
    .filter((value): value is string => value !== undefined)
    .map((value) => legible(flatten(parseColor(value), canvas)));
  const preferred = candidates[0] ?? legible(canvas);
  const usable = candidates.find(clear);
  if (usable !== undefined) return toHex(usable);

  // Nothing in the palette is far enough from all three. Rotate instead: the nearest legible turn
  // of the hue circle that clears the gap, which holds the palette's own lightness.
  const rotated = moves(preferred);
  const turned = rotated.find(clear);
  if (turned !== undefined) return toHex(turned);

  // A monochrome palette has no hue to turn, and its lightness axis is already crowded — mono-dark
  // puts number, string and property at 0.68, 0.77 and 0.92, and pins the floor at 0.58. On one
  // axis the best position is always an end of the readable band or the middle of a gap between two
  // neighbours, so solve for those exactly rather than sweeping a grid: the grid's 0.03 step misses
  // the floor by 0.01 and loses a gap that is actually there.
  const polar = oklch(preferred);
  const at = (lightness: number): Rgb => fromOklch({ ...polar, l: lightness });
  const [low, high] = readableBand(readable, at);
  const inside = neighbours
    .map((neighbour) => oklch(neighbour).l)
    .filter((lightness) => lightness > low && lightness < high)
    .sort((a, b) => a - b);
  const edges = [low, ...inside, high];
  const places = [low, high, ...edges.slice(1).map((edge, index) => ((edges[index] ?? low) + edge) / HALF)];

  return toHex(furthest(preferred, [...places.map(at), ...rotated]));
}

function shadowFor(canvas: Rgb, lighter: boolean): string {
  const recipe = lighter ? SHADOW.dark : SHADOW.light;
  const tinted = mix(canvas, BLACK, recipe.toward);
  const channel = (value: number): number => Math.round(value);
  return `${SHADOW_GEOMETRY} rgb(${channel(tinted.r)} ${channel(tinted.g)} ${channel(tinted.b)} / ${recipe.alpha.toFixed(ALPHA_DECIMALS)})`;
}

function familyOf(id: string): string {
  const known = Object.keys(ATTRIBUTION)
    .filter((family) => id === family || id.startsWith(`${family}-`))
    .sort((a, b) => b.length - a.length);
  const best = known[0];
  if (best === undefined) throw new Error(`no attribution for ${id}`);
  return best;
}

interface Generated extends AuditableTheme {
  readonly name: string;
  readonly source: string;
  readonly licence: string;
  readonly shadowFloat: string;
}

function convert(palette: Palette, overrides: Overrides): Generated {
  const { metadata } = palette;
  const id = metadata.id;
  const lighter = metadata.variant === "dark";
  const extreme = lighter ? WHITE : BLACK;
  const source = palette.colors;
  const surfaceOf = (key: string): string => read(source.surface, key, `${id}.surface`);

  const canvasSeed = opaque(surfaceOf("background"), BLACK);
  const seeds = [
    canvasSeed,
    opaque(surfaceOf("muted"), canvasSeed),
    opaque(surfaceOf("elevated"), canvasSeed),
    opaque(surfaceOf("subtle"), canvasSeed),
  ];
  const [canvas = canvasSeed, panel = canvasSeed, control = canvasSeed, hover = canvasSeed] = respaceLadder(
    seeds,
    lighter,
  );

  const accentSeed = opaque(read(source.primary, "base", `${id}.primary`), canvas);
  const accent = escalate(accentSeed, [canvas, panel], CONTRAST_TARGET.accentForeground * MARGIN, extreme);

  // `interactive.selection` is an overlay in the source, and preman's selected row is a solid fill.
  // Flatten it, pull it toward the accent, then put it back on `hover`'s luminance: the whole rule
  // is that selection is a *tint* at hover brightness, so every ink tier stays legible on it.
  const selected = toLuminance(
    mix(opaque(read(source.interactive, "selection", `${id}.interactive`), canvas), accent, SELECTION_TINT),
    luminance(hover),
  );

  const surfaces = [canvas, panel, control, hover, selected];
  const ink = escalate(opaque(surfaceOf("foreground"), canvas), surfaces, CONTRAST_TARGET.ink * MARGIN, extreme);
  const fade = (target: number): Rgb => fadeToTarget(ink, canvas, surfaces, target * MARGIN);

  const status = (key: string): Rgb =>
    escalate(
      opaque(read(source.status, key, `${id}.status`), canvas),
      [canvas, panel],
      CONTRAST_TARGET.method * MARGIN,
      extreme,
    );

  const colors: Record<string, string> = {
    canvas: toHex(canvas),
    panel: toHex(panel),
    control: toHex(control),
    hover: toHex(hover),
    selected: toHex(selected),
    line: toHex(opaque(read(source.interactive, "border", `${id}.interactive`), panel)),
    "line-strong": toHex(opaque(read(source.interactive, "borderHover", `${id}.interactive`), panel)),
    ink: toHex(ink),
    "ink-dim": toHex(fade(CONTRAST_TARGET.inkDim)),
    "ink-faint": toHex(fade(CONTRAST_TARGET.inkFaint)),
    glyph: toHex(fade(CONTRAST_TARGET.glyph)),
    accent: toHex(accent),
    ok: toHex(status("success")),
    warn: toHex(status("warning")),
    danger: toHex(status("error")),
    ...methodColumn(source, canvas, panel, extreme),
    ...(overrides[id]?.colors ?? {}),
  };

  const syntaxOf = (group: string, key: string): string | undefined => {
    if (group === "base") return source.syntax.base[key];
    if (group === "tokens") return source.syntax.tokens[key];
    return source.syntax.highlights[key];
  };
  const syntax: Record<string, string> = {};
  for (const [token, { from, or }] of Object.entries(SYNTAX_SOURCES)) {
    const raw = syntaxOf(from[0], from[1]) ?? (or === undefined ? undefined : syntaxOf(or[0], or[1]));
    if (raw === undefined) throw new Error(`${id} has no source for --syntax-${token}`);
    syntax[token] = toHex(escalate(opaque(raw, panel), [canvas, panel], CONTRAST_TARGET.method * MARGIN, extreme));
  }
  const elsewhere: Record<(typeof SYNTAX_ELSEWHERE)[number], string> = {
    invalid: read(source.status, "error", `${id}.status`),
    heading: read(source.markdown, "heading1", `${id}.markdown`),
    link: read(source.markdown, "link", `${id}.markdown`),
  };
  for (const token of SYNTAX_ELSEWHERE) {
    syntax[token] = toHex(
      escalate(opaque(elsewhere[token], panel), [canvas, panel], CONTRAST_TARGET.method * MARGIN, extreme),
    );
  }

  // Last, because it is solved against the three tokens above rather than read from a slot.
  const neighbours = TEMPLATE_NEIGHBOURS.map((token) => {
    const hex = syntax[token];
    if (hex === undefined) throw new Error(`${id} has no --syntax-${token} to separate the template token from`);
    return parseColor(hex);
  });
  syntax.template = templateColour(source, neighbours, canvas, panel, extreme);

  Object.assign(syntax, overrides[id]?.syntax ?? {});

  const attribution = ATTRIBUTION[familyOf(id)];
  if (attribution === undefined) throw new Error(`no attribution for ${id}`);

  return {
    id,
    name: metadata.name,
    variant: lighter ? "dark" : "light",
    source: attribution.source,
    licence: attribution.licence,
    colors,
    syntax,
    shadowFloat: shadowFor(canvas, lighter),
  };
}

function identifierFor(id: string): string {
  return id.replace(/-([a-z0-9])/g, (_match, character: string) => character.toUpperCase());
}

function serialise(theme: Generated): string {
  const entries = (record: Readonly<Record<string, string>>): string =>
    Object.entries(record)
      .map(([token, value]) => `    ${JSON.stringify(token)}: ${JSON.stringify(value)},`)
      .join("\n");
  return `${HEADER}
import type { Theme } from "@preman/desktop/renderer/appearance/theme.js";

export const ${identifierFor(theme.id)}: Theme = {
  id: ${JSON.stringify(theme.id)},
  name: ${JSON.stringify(theme.name)},
  variant: ${JSON.stringify(theme.variant)},
  source: ${JSON.stringify(theme.source)},
  licence: ${JSON.stringify(theme.licence)},
  colors: {
${entries(theme.colors)}
  },
  syntax: {
${entries(theme.syntax)}
  },
  shadowFloat: ${JSON.stringify(theme.shadowFloat)},
};
`;
}

/**
 * One module with static imports, and no lazy split.
 *
 * Forty-three themes of about fifty-six values each is roughly 2,400 hex strings, which V8 parses
 * in single-digit milliseconds. A lazy body would save a few of those and make a theme change
 * `async`, which then has to interact with the apply-before-first-paint path.
 */
function serialiseIndex(ids: readonly string[]): string {
  const imports = ids.map((id) => `import { ${identifierFor(id)} } from "./${id}.js";`).join("\n");
  return `${HEADER}
import type { Theme } from "@preman/desktop/renderer/appearance/theme.js";
${imports}

/** Every bundled theme, ${JSON.stringify(HAND_WRITTEN)} first because it is the default. */
export const THEMES: readonly Theme[] = [${ids.map(identifierFor).join(", ")}];
`;
}

/**
 * The output is committed, so it is held to the same formatting as anything else in the tree —
 * `format:check` does not know a file was written by a script. Running Prettier here, rather than
 * ignoring the directory, keeps the generated modules and the hand-written `preman-dark.ts` beside
 * them under one rule.
 */
async function write(file: string, source: string): Promise<void> {
  const options = await resolveConfig(file);
  writeFileSync(file, await format(source, { ...options, filepath: file }), ENCODING);
}

async function main(): Promise<void> {
  const overrides: Overrides = JSON.parse(readFileSync(OVERRIDE_FILE, ENCODING)) as Overrides;
  const files = readdirSync(PALETTE_DIR)
    .filter((file) => file.endsWith(JSON_EXTENSION) && file !== "overrides.json")
    .sort();

  const generated: Generated[] = [];
  for (const file of files) {
    const palette = JSON.parse(readFileSync(join(PALETTE_DIR, file), ENCODING)) as Palette;
    generated.push(convert(palette, overrides));
  }

  let failed = 0;
  for (const theme of generated) {
    const violations = auditTheme(theme);
    if (violations.length === 0) continue;
    failed += 1;
    process.stdout.write(`${theme.id}\n${violations.map((line) => `  ${line}`).join("\n")}\n`);
  }

  for (const theme of generated) {
    await write(join(OUTPUT_DIR, `${theme.id}.ts`), serialise(theme));
  }
  await write(join(OUTPUT_DIR, "index.ts"), serialiseIndex([HAND_WRITTEN, ...generated.map((theme) => theme.id)]));

  process.stdout.write(
    `${String(generated.length)} palettes converted, ${String(failed)} with violations, ` +
      `${String(SURFACE_MIN_STEP)} minimum ladder step, ${String(METHOD_TOKENS.length)} method colours each\n`,
  );
  if (failed > 0) process.exitCode = EXIT_FAILURE;
}

await main();
